### ISSUE TITLE
구글 extension에서 삭제 되었네요.

### ISSUE THREAD

**Issue by hira66it** [ttop32/MouseTooltipTranslator#1]
확인 부탁드려요

**Comment by ttop32** [comment]
3/18일쯤에 해당 확장 프로그램 동작이 아예 안되기에 
제 손으로 급하게 설치 페이지를 내렸습니다

문제 파악해보니 구글 번역 서버에 변동이 있어서 
해당 문제를 고친 0.1.15으로 업데이트 하였습니다

해당 버전을 chrome web store에 리뷰를 맡긴지
얼마안되기에 시간이 다소걸릴거같습니다

사용이 급하시면
크롬 확장 설정 페이지에서 개발자 모드를 통해
압축해제된 확장 로드를 통해 아래 프로그램을 사용하시기 바랍니다
https://github.com/ttop32/MouseTooltipTranslator/raw/main/build.zip

**Comment by hira66it** [comment]
확인 감사합니다.
