### ISSUE TITLE
the lastest version use too much cpu

### ISSUE THREAD

**Issue by tranhongs0n** [ttop32/MouseTooltipTranslator#10]
hey, I love your extension, it's very helpful. But the lastest version has some bugs or something which make my browser always use more 20% cpu and power usage is very high.
Hope you fix it soon.

**Comment by ttop32** [comment]
new v0.1.31 is on chrome store
can you tell me is still high or not
I am not sure about bug is gone completely

**Comment by tranhongs0n** [comment]
It's better now. Thanks for your contribution to the community.
