### ISSUE TITLE
Github Security Lab Vulnerability Report

### ISSUE THREAD

**Issue by Kwstubbs** [ttop32/MouseTooltipTranslator#101]
Hello, Github Security Lab has found a vulnerability in MouseTooltipTranslator. Please enable [private-vulnerability-reporting](https://docs.github.com/en/code-security/security-advisories/working-with-repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository) or provide a point of contact so that we can help you fix this issue.

**Comment by ttop32** [comment]
private-vulnerability-reporting is opened. Thank you.
