### ISSUE TITLE
설치 후 디셀렉트가 잘 안돼요.

### ISSUE THREAD

**Issue by prvDevs** [ttop32/MouseTooltipTranslator#123]
이 확장을 설치한 이 후로 문장을 드래그 해서 선택을 한 후에 해당 페이지의 아무 곳이나 클릭해서 눌러서 디셀렉트 할때 두번, 세번씩 눌러야 디셀렉트 되는 경우가 매우 흔해졌습니다.

혹시 이게 이 확장 기능과 관계가 있나요.

**Comment by rishubil** [comment]
동일한 문제가 발생하고 있는데 혹시 해결하셨나요?

**Comment by rishubil** [comment]
확실한지는 모르겠지만, 0.1.209 버전 업데이트 후 이 증상도 사라졌습니다.

**Comment by rishubil** [comment]
> 확실한지는 모르겠지만, 0.1.209 버전 업데이트 후 이 증상도 사라졌습니다.

정확한 버그 재현 방법을 몰라 이렇게 생각했었는데, 0.1.210에서 동일한 증상을 발견하여 신규 이슈로 등록했습니다.
