### ISSUE TITLE
strange bug : the microphone is triggered in Google Chrome when press the RCtrl button

### ISSUE THREAD

**Issue by Enlight432** [ttop32/MouseTooltipTranslator#133]
This is my reddit post: (After checking this problem, I found out that the problem is with MouseTooltipTranslator extension, whenever I disable it, this problem is solved)

https://www.reddit.com/r/chrome/comments/1cs4jr8/the_strangest_problem_in_history_the_microphone/

It is very very strange

When I press the RCtrl button on the keybooard ,A request to activate the microphone for that site will pop up (Image below)

https://i.imgur.com/IE0cAoP.png

LCtrl does not have this problem

This problem exists in every site

This problem does not exist in Microsoft Edge

I killed all the programs and tested again, but this problem still exists

OS : Windows 10

Google Chrome is always updated

**Comment by ttop32** [comment]
I recently added speech recognition translate feature
You can change key from SPEECH - speech recogntion when

**Comment by Enlight432** [comment]
@ttop32
Thank you bro
