### ISSUE TITLE
How to work with file pdf read on browser ?

### ISSUE THREAD

**Issue by ThorPham** [ttop32/MouseTooltipTranslator#3]
Extention can work with file pdf ?

**Comment by ttop32** [comment]
first of all, you need to set “allow access to file URLs”  from chrome://extensions/?id=hmigninkgibhdckiaphhmbgcghochdjc

then, open pdf file with chrome will automactically redirect to mouse tooltip translator's pdf.js viwer

if other pdf related extension is installed, it will be crashed

And, It only works on text pdf file

**Comment by ThorPham** [comment]
Thank you it worked .
