### ISSUE TITLE
When 'Voice Target' is 'Source Text' it should auto-detect the language and use a voice of that language

### ISSUE THREAD

**Issue by AstudilloMarillo** [ttop32/MouseTooltipTranslator#62]
Don't know if this is possible, but it would be very welcome if the voice could speak in a language of the auto-detected text. So when I select a Spanish text (which is foreign to me), I can listen to how to pronounce that text. Same for Italian, German, etc. It adds no value to me when I select Spanish text and the app tries to pronounce it in English.

**Comment by marcello-pietrobon** [comment]
Is it possible to know why this issue has been closed though it doesn't seem working? It would be very useful if it would be working.

**Comment by AstudilloMarillo** [comment]
> Is it possible to know why this issue has been closed though it doesn't seem working? It would be very useful if it would be working.

I closed it because it works for me. I select English text and press my voice activation key: it speaks English with a correct English voice. I select Spanish text and press my voice activation key: it speaks Spanish with a correct Spanish voice. Same with any other language I select text of.  That is what I asked for, so I'm happy.

I guess these are the settings that are most important for it:
![image](https://github.com/ttop32/MouseTooltipTranslator/assets/136191659/4f00ea82-0425-4521-881e-ca7938dd37ae)

![image](https://github.com/ttop32/MouseTooltipTranslator/assets/136191659/1c1e590e-3837-4631-8b27-5e0b8a016b3b)

**Comment by marcello-pietrobon** [comment]
Thank you, now it's clear and it works, I may have overlooked something.

Would it be good to add this in the [how-to-use](https://github.com/ttop32/MouseTooltipTranslator/blob/main/doc/intro.md#how-to-use) page,

or maybe set as default Voice Target=Translated Text ?
