### ISSUE TITLE
Feature Requests: Adding other meanings in "Word mode"

### ISSUE THREAD

**Issue by Enlight432** [ttop32/MouseTooltipTranslator#96]
It would be great if it also said synonyms in "Word mode" (such as "simple translate" extension) because every word has several meanings and seeing only one meaning sometimes does not solve the problem and This helps the language learning process a lot

![image](https://github.com/ttop32/MouseTooltipTranslator/assets/123282471/9a7a4e67-0fc7-4e0a-b527-81860311f72e)

**Comment by Enlight432** [comment]
This item was added
thank you very much

**Comment by seregadushka** [comment]
Yes , sinonims  must be, tnx
